# documenation https://docs.docker.com/compose/yml/

namenode:
  build: .
  hostname: namenode
  container_name: hadoop_namenode
  volumes:
    - ./shared/hdfs/namenode:/shared/dfs/namenode
  ports:
    - "8020:8020"
    - "50070:50070"
  command: hdfs namenode

datanode1:
  build: .
  hostname: datanode1
  container_name: hadoop_datanode1
  volumes:
    - ./shared/hdfs/datanode1:/shared/dfs/datanode1
  links:
      - namenode
  ports:
      - "5001:50075"
  command: hdfs datanode

datanode2:
  build: .
  hostname: datanode2
  container_name: hadoop_datanode2
  volumes:
    - ./shared/hdfs/datanode1:/shared/dfs/datanode1
  links:
      - namenode
  ports:
      - "5002:50075"
  command: hdfs datanode

datanode3:
  build: .
  hostname: datanode3
  container_name: hadoop_datanode3
  volumes:
    - ./shared/hdfs/datanode1:/shared/dfs/datanode1
  links:
      - namenode
  ports:
      - "5003:50075"
  command: hdfs datanode
