# documenation https://docs.docker.com/compose/yml/

namenode:
  build: .
  hostname: namenode
  container_name: dfs_namenode
  volumes:
    - ./shared/hdfs/namenode:/shared/dfs/namenode
  ports:
    - "8020:8020"
    - "50070:50070"
  command: hdfs namenode

datanode1:
  build: .
  hostname: datanode1
  container_name: dfs_datanode1
  volumes:
    - ./shared/hdfs/datanode1:/shared/dfs/datanode1
  links:
      - namenode
  ports:
      - "5001:50075"
  command: hdfs datanode

datanode2:
  build: .
  hostname: datanode2
  container_name: dfs_datanode2
  volumes:
    - ./shared/hdfs/datanode2:/shared/dfs/datanode2
  links:
      - namenode
  ports:
      - "5002:50075"
  command: hdfs datanode

datanode3:
  build: .
  hostname: datanode3
  container_name: dfs_datanode3
  volumes:
    - ./shared/hdfs/datanode3:/shared/dfs/datanode3
  links:
      - namenode
  ports:
      - "5003:50075"
  command: hdfs datanode

redis:
  image: redis
  hostname: redis
  container_name: redis

hsqldb:
  image: springxd/hsqldb
  hostname: hsqldb
  container_name: hsqldb

zookeeper:
  image: jplock/zookeeper
  hostname: zookeeper
  container_name: zookeeper
  ports:
   - "2181:2181"
   - "2888:2888"
   - "3888:3888"

admin:
  image: springxd/admin
  hostname: admin
  container_name: admin
  volumes:
    - ./shared/admin:/shared
  ports:
   - "9393:9393"
  links:
   - zookeeper:zookeeper
   - redis:redis
   - hsqldb:hsqldb

container:
  image: springxd/container
  hostname: container
  container_name: container
  volumes:
    - ./shared/admin:/shared
  links:
   - zookeeper:zookeeper
   - redis:redis
   - hsqldb:hsqldb 
